### Particle Image Function
### Version: 1.0.4
### Width: 20
### Height: 20
### ParticleType: large_smoke

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

execute at @s run playsound minecraft:block.anvil.land record @s ~ ~ ~ 1 1

particle minecraft:large_smoke ~2.7 ~0 ~-1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.7 ~0 ~-0.9 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.7 ~0 ~-0.6 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.7 ~0 ~-0.3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.7 ~0 ~0 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.7 ~0 ~0.3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.7 ~0 ~0.6 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.4 ~0 ~-1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.4 ~0 ~-1.5 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.4 ~0 ~-1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.4 ~0 ~0.6 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.4 ~0 ~0.9 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.4 ~0 ~1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.1 ~0 ~-2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.1 ~0 ~-1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.1 ~0 ~1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~2.1 ~0 ~1.5 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.8 ~0 ~-2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.8 ~0 ~-2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.8 ~0 ~1.5 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.8 ~0 ~1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.5 ~0 ~-2.7 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.5 ~0 ~-2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.5 ~0 ~1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.5 ~0 ~2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.2 ~0 ~-2.7 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~1.2 ~0 ~2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.9 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.9 ~0 ~-2.7 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.9 ~0 ~2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.9 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.6 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.6 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.3 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0.3 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~0 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.3 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.3 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.6 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.6 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.9 ~0 ~-3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.9 ~0 ~-2.7 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.9 ~0 ~2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-0.9 ~0 ~2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.2 ~0 ~-2.7 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.2 ~0 ~2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.5 ~0 ~-2.7 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.5 ~0 ~-2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.5 ~0 ~1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.5 ~0 ~2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.8 ~0 ~-2.4 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.8 ~0 ~-2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.8 ~0 ~1.5 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-1.8 ~0 ~1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.1 ~0 ~-2.1 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.1 ~0 ~-1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.1 ~0 ~1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.1 ~0 ~1.5 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.4 ~0 ~-1.8 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.4 ~0 ~-1.5 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.4 ~0 ~-1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.4 ~0 ~0.6 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.4 ~0 ~0.9 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.4 ~0 ~1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~-1.2 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~-0.9 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~-0.6 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~-0.3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~0 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~0.3 0 0 0 0 1 normal @s
particle minecraft:large_smoke ~-2.7 ~0 ~0.6 0 0 0 0 1 normal @s
